name: Git Action Test

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run docs:build

    - name: SFTP Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          ARGS: "-avz --delete"
          SOURCE: "./docs/.vuepress/dist/"
          REMOTE_HOST: "139.196.82.33"
          REMOTE_USER: "root"
          TARGET: "/webSrc/"