name: Git Action Test

on:
  push:
    branches:
    - master

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - run: npm install
    - run: npm run docs:build

    - name: deploy file to server
        uses: peaceiris/actions-gh-pages@v2
        with:  
          username: 'root'   
          server: '139.196.82.33'
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
          local_path: 'docs/.vuepress/dist'
          remote_path: '/webSrc/'